services:
  - type: web
    name: call-center-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DIALPAD_BEARER_TOKEN
        sync: false
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true
