services:
  - type: web
    name: call-center-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --log-level debug
    envVars:
      - key: DIALPAD_BEARER_TOKEN
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: dashboard-redis
          property: connectionString
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true

  - type: redis
    name: dashboard-redis
    ipAllowList: []
    plan: free
